<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SteamStopper</AssemblyName>
    <RootNamespace>SteamStopper</RootNamespace>
    <Product>Steam Stopper</Product>
    <ApplicationTitle>Steam Stopper</ApplicationTitle>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>2.1.0</Version>
    <FileVersion>2.1.0</FileVersion>
    <AssemblyVersion>2.1.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <Content Include="FeedUrl.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
